// Typed NovelAI sampling preset catalog: generated from the former 03_nai_presets.sql seed.

import type { CatalogSection, NaiPresetInput } from "./types";

export const naiPresetSections: CatalogSection<NaiPresetInput>[] = [
  {
    comment: ["============ KAYRA PRESETS ============", "Carefree-Kayra (DEFAULT for kayra-v1)"],
    rows: [
      {
        name: "Carefree-Kayra",
        modelTarget: "kayra",
        isDefault: true,
        desc: "Balanced and relaxed, a reliable all-purpose preset for natural roleplay.",
        i18n: {
          ja: "バランスが取れたリラックスしたプリセット。自然なロールプレイに最適。",
          "pt-BR": "Equilibrada e relaxada, uma predefinição versátil e confiável para roleplay natural.",
          "es-419": "Equilibrado y relajado, preajuste confiable para roleplay natural.",
        },
        parameters: {
          order: [2, 3, 0, 4, 1],
          temperature: 1.35,
          max_length: 150,
          min_length: 1,
          top_k: 15,
          top_p: 0.85,
          top_a: 0.1,
          tail_free_sampling: 0.915,
          repetition_penalty: 2.8,
          repetition_penalty_range: 2048,
          repetition_penalty_slope: 0.02,
          repetition_penalty_frequency: 0.02,
          repetition_penalty_presence: 0,
          phrase_rep_pen: "aggressive",
          min_p: 0,
        },
      },
    ],
  },
  {
    comment: "Asper-Kayra",
    rows: [
      {
        name: "Asper-Kayra",
        modelTarget: "kayra",
        desc: "Crisp and focused, lower temperature with Typical Sampling for steady, disciplined prose.",
        i18n: {
          ja: "温度低めでTypical Samplingを使用。落ち着いた規律ある文体に最適。",
          "pt-BR": "Focada e precisa, temperatura menor com Typical Sampling para prosa firme e disciplinada.",
          "es-419": "Preciso y enfocado, con menor temperatura y Typical Sampling para prosa firme.",
        },
        parameters: {
          order: [5, 0, 1, 3],
          temperature: 1.16,
          max_length: 150,
          min_length: 1,
          top_k: 175,
          typical_p: 0.96,
          tail_free_sampling: 0.994,
          repetition_penalty: 1.68,
          repetition_penalty_range: 2240,
          repetition_penalty_slope: 1.5,
          repetition_penalty_frequency: 0,
          repetition_penalty_presence: 0.005,
          phrase_rep_pen: "medium",
          min_p: 0,
        },
      },
    ],
  },
  {
    comment: "Blended-Coffee-Kayra",
    rows: [
      {
        name: "Blended-Coffee-Kayra",
        modelTarget: "kayra",
        desc: "Smooth and grounded, blends top-K and tail-free for consistent, natural storytelling.",
        i18n: {
          ja: "トップKとテールフリーを組み合わせた滑らかで安定した文体。",
          "pt-BR": "Suave e realista, mistura top-K e tail-free para narração natural e consistente.",
          "es-419": "Suave y estable, combina top-K y tail-free para una narración natural.",
        },
        parameters: {
          order: [0, 1, 2, 3],
          temperature: 1.0,
          max_length: 150,
          min_length: 1,
          top_k: 25,
          top_p: 1.0,
          tail_free_sampling: 0.925,
          repetition_penalty: 1.6,
          repetition_penalty_frequency: 0.001,
          repetition_penalty_range: 0,
          repetition_penalty_presence: 0,
          phrase_rep_pen: "medium",
          min_p: 0,
        },
      },
    ],
  },
  {
    comment: "Blook-Kayra",
    rows: [
      {
        name: "Blook-Kayra",
        modelTarget: "kayra",
        desc: "Bold repetition-fighter, very aggressive phrase rep penalty keeps outputs fresh and varied.",
        i18n: {
          ja: "非常に攻撃的なフレーズ繰り返しペナルティで新鮮でバラエティ豊かな出力を実現。",
          "pt-BR": "Combate repetições, penalidade de frase agressiva mantém as respostas variadas.",
          "es-419": "Combate repeticiones con una penalización agresiva para respuestas variadas.",
        },
        parameters: {
          order: [2, 3, 1, 0],
          temperature: 1.0,
          max_length: 150,
          min_length: 1,
          top_k: 0,
          top_p: 0.96,
          tail_free_sampling: 0.96,
          repetition_penalty: 2.0,
          repetition_penalty_slope: 1.0,
          repetition_penalty_frequency: 0.02,
          repetition_penalty_range: 0,
          repetition_penalty_presence: 0.3,
          phrase_rep_pen: "very_aggressive",
          min_p: 0,
        },
      },
    ],
  },
  {
    comment: "CosmicCube-Kayra",
    rows: [
      {
        name: "CosmicCube-Kayra",
        modelTarget: "kayra",
        desc: "Mirostat entropy sampling, experimental entropy-based sampler for unpredictable, cosmic outputs.",
        i18n: {
          ja: "ミロスタットエントロピーサンプリング。予測不可能で宇宙的な出力のための実験的サンプラー。",
          "pt-BR": "Amostragem Mirostat, experimental para respostas cósmicas e imprevisíveis.",
          "es-419": "Muestreo de entropía Mirostat para resultados cósmicos e impredecibles.",
        },
        parameters: {
          order: [8, 5, 0, 3],
          temperature: 0.9,
          max_length: 150,
          min_length: 1,
          typical_p: 0.95,
          tail_free_sampling: 0.92,
          mirostat_lr: 0.22,
          mirostat_tau: 4.95,
          repetition_penalty: 3.0,
          repetition_penalty_range: 4000,
          repetition_penalty_frequency: 0,
          repetition_penalty_presence: 0,
          phrase_rep_pen: "off",
          min_p: 0,
        },
      },
    ],
  },
  {
    comment: "Fresh-Coffee-Kayra",
    rows: [
      {
        name: "Fresh-Coffee-Kayra",
        modelTarget: "kayra",
        desc: "Light and clean, fresher top-K outputs with minimal phrase repetition penalty.",
        i18n: {
          ja: "軽くクリーンなトップK出力。フレーズ繰り返しペナルティを最小化。",
          "pt-BR": "Leve e limpa, respostas top-K com penalidade mínima de repetição de frase.",
          "es-419": "Ligero y limpio, con salidas top-K frescas y mínima penalización de repetición.",
        },
        parameters: {
          order: [0, 1, 2, 3],
          temperature: 1.0,
          max_length: 150,
          min_length: 1,
          top_k: 25,
          top_p: 1.0,
          tail_free_sampling: 0.925,
          repetition_penalty: 1.9,
          repetition_penalty_range: 768,
          repetition_penalty_slope: 1.0,
          repetition_penalty_frequency: 0.0025,
          repetition_penalty_presence: 0.001,
          phrase_rep_pen: "off",
          min_p: 0,
        },
      },
    ],
  },
  {
    comment: "Green-Active-Writer-Kayra",
    rows: [
      {
        name: "Green-Active-Writer-Kayra",
        modelTarget: "kayra",
        desc: "High-energy mirostat writer, creative and dynamic at temperature 1.5 with strong anti-repetition.",
        i18n: {
          ja: "高エネルギーなミロスタットライター。温度1.5で創造的かつダイナミック、強い反復防止付き。",
          "pt-BR": "Mirostat de alta energia, dinâmico e criativo (temp 1.5) com forte antirrepetição.",
          "es-419": "Mirostat enérgico y creativo (temp. 1.5) con fuerte control de repeticiones.",
        },
        parameters: {
          order: [0, 8, 5, 3],
          temperature: 1.5,
          max_length: 150,
          min_length: 1,
          typical_p: 0.95,
          tail_free_sampling: 0.95,
          mirostat_lr: 0.2,
          mirostat_tau: 5.5,
          repetition_penalty: 1.0,
          repetition_penalty_range: 1632,
          repetition_penalty_frequency: 0,
          repetition_penalty_presence: 0,
          phrase_rep_pen: "very_aggressive",
          min_p: 0,
        },
      },
    ],
  },
  {
    comment: "Pilotfish-Kayra",
    rows: [
      {
        name: "Pilotfish-Kayra",
        modelTarget: "kayra",
        desc: "Multi-sampler blend, layered top-K/P/A/Typical for rich narrative variety.",
        i18n: {
          ja: "複数のサンプラーを組み合わせた豊かなナラティブバリエーション。",
          "pt-BR": "Mistura de amostradores top-K/P/A/Typical para rica variedade de narração.",
          "es-419": "Mezcla top-K/P/A/Typical para una gran variedad narrativa.",
        },
        parameters: {
          order: [0, 4, 1, 2, 5, 3],
          temperature: 1.31,
          max_length: 150,
          min_length: 1,
          top_k: 25,
          top_p: 0.97,
          top_a: 0.18,
          typical_p: 0.98,
          tail_free_sampling: 1.0,
          repetition_penalty: 1.55,
          repetition_penalty_frequency: 0.00075,
          repetition_penalty_presence: 0.00085,
          repetition_penalty_range: 8192,
          repetition_penalty_slope: 1.8,
          phrase_rep_pen: "medium",
          min_p: 0,
        },
      },
    ],
  },
  {
    comment: "Pro_Writer-Kayra",
    rows: [
      {
        name: "Pro_Writer-Kayra",
        modelTarget: "kayra",
        desc: "Refined narrative, tuned for written prose quality using top-A and Typical Sampling.",
        i18n: {
          ja: "洗練されたナラティブ。トップAとTypical Samplingによる高品質な文章向け。",
          "pt-BR": "Narrativa refinada, ajustada para qualidade de prosa (top-A e Typical Sampling).",
          "es-419": "Narrativa refinada, optimizada para prosa de calidad con top-A y Typical Sampling.",
        },
        parameters: {
          order: [3, 4, 5, 0],
          temperature: 1.06,
          max_length: 150,
          min_length: 1,
          top_a: 0.146,
          typical_p: 0.976,
          tail_free_sampling: 0.969,
          repetition_penalty: 1.86,
          repetition_penalty_slope: 2.33,
          repetition_penalty_frequency: 0,
          repetition_penalty_presence: 0,
          repetition_penalty_range: 2048,
          phrase_rep_pen: "medium",
          min_p: 0,
        },
      },
    ],
  },
  {
    comment: "Stelenes-Kayra",
    rows: [
      {
        name: "Stelenes-Kayra",
        modelTarget: "kayra",
        desc: "Maximum chaos, very high temperature (2.5) for maximally experimental and unpredictable text.",
        i18n: {
          ja: "最大カオス。温度2.5による極めて実験的で予測不可能なテキスト生成。",
          "pt-BR": "Caos máximo (temp 2.5) para textos extremamente experimentais e imprevisíveis.",
          "es-419": "Caos máximo, temperatura muy alta (2.5) para texto experimental e impredecible.",
        },
        parameters: {
          order: [3, 0, 5],
          temperature: 2.5,
          max_length: 150,
          min_length: 1,
          typical_p: 0.969,
          tail_free_sampling: 0.941,
          repetition_penalty: 1.0,
          repetition_penalty_range: 1024,
          repetition_penalty_frequency: 0,
          repetition_penalty_presence: 0,
          phrase_rep_pen: "medium",
          min_p: 0,
        },
      },
    ],
  },
  {
    comment: "Tea_Time-Kayra",
    rows: [
      {
        name: "Tea_Time-Kayra",
        modelTarget: "kayra",
        desc: "Quiet and mellow, top-A and Typical with aggressive phrase guard for tranquil outputs.",
        i18n: {
          ja: "トップAとTypical、攻撃的フレーズガードで穏やかで落ち着いた出力を実現。",
          "pt-BR": "Calma e suave, top-A e Typical com guarda de frase agressiva para saídas tranquilas.",
          "es-419": "Tranquilo y suave, top-A y Typical con control agresivo de frases.",
        },
        parameters: {
          order: [5, 0, 4],
          temperature: 1.0,
          max_length: 150,
          min_length: 1,
          top_a: 0.017,
          typical_p: 0.975,
          repetition_penalty: 3.0,
          repetition_penalty_slope: 0.09,
          repetition_penalty_frequency: 0,
          repetition_penalty_presence: 0,
          repetition_penalty_range: 7680,
          phrase_rep_pen: "aggressive",
          min_p: 0,
        },
      },
    ],
  },
  {
    comment: "Tesseract-Kayra",
    rows: [
      {
        name: "Tesseract-Kayra",
        modelTarget: "kayra",
        desc: "Sharp and precise, very low temperature (0.895) for highly deterministic, focused responses.",
        i18n: {
          ja: "非常に低い温度（0.895）による高度に決定論的でフォーカスした応答。",
          "pt-BR": "Afiada e precisa, temperatura baixa (0.895) para respostas determinísticas.",
          "es-419": "Agudo y preciso, temperatura muy baja (0.895) para respuestas deterministas.",
        },
        parameters: {
          order: [0, 5],
          temperature: 0.895,
          max_length: 150,
          min_length: 1,
          typical_p: 0.9,
          repetition_penalty: 2.0,
          repetition_penalty_slope: 3.2,
          repetition_penalty_frequency: 0,
          repetition_penalty_presence: 0,
          repetition_penalty_range: 4048,
          phrase_rep_pen: "aggressive",
          min_p: 0,
        },
      },
    ],
  },
  {
    comment: "Writers-Daemon-Kayra",
    rows: [
      {
        name: "Writers-Daemon-Kayra",
        modelTarget: "kayra",
        desc: "Daemon-driven mirostat, comprehensive multi-sampler with high entropy for creative writing.",
        i18n: {
          ja: "デーモン駆動のミロスタット。高エントロピーの包括的マルチサンプラーでクリエイティブライティングに最適。",
          "es-419": "Mirostat impulsado por daemon, con alta entropía para escritura creativa.",
        },
        parameters: {
          order: [8, 0, 5, 3, 2, 4],
          temperature: 1.5,
          max_length: 150,
          min_length: 1,
          top_a: 0.02,
          top_p: 0.95,
          typical_p: 0.95,
          tail_free_sampling: 0.95,
          mirostat_lr: 0.25,
          mirostat_tau: 5.0,
          repetition_penalty: 1.625,
          repetition_penalty_range: 2016,
          repetition_penalty_frequency: 0,
          repetition_penalty_presence: 0,
          phrase_rep_pen: "very_aggressive",
          min_p: 0,
        },
      },
    ],
  },
  {
    comment: ["============ ERATO PRESETS ============", "Erato-Shosetsu (DEFAULT for llama-3-erato-v1)"],
    rows: [
      {
        name: "Erato-Shosetsu",
        modelTarget: "erato",
        isDefault: true,
        desc: "Novel-style writing, Shosetsu (小説) tuned for structured narrative with strong rep control.",
        i18n: {
          ja: "「小説」スタイル。整理されたナラティブと強い反復制御に最適化。",
          "pt-BR": "Estilo romance, Shosetsu (小説) ajustado para narrativa estruturada e controle de repetição.",
          "es-419": "Estilo novela, Shosetsu (小説) para narrativa estructurada y control de repeticiones.",
        },
        parameters: {
          order: [9, 10],
          temperature: 1.0,
          max_length: 150,
          min_length: 1,
          top_k: 50,
          top_p: 0.85,
          top_a: 1.0,
          typical_p: 1.0,
          tail_free_sampling: 0.895,
          repetition_penalty: 1.63,
          repetition_penalty_range: 1024,
          repetition_penalty_slope: 3.33,
          repetition_penalty_frequency: 0.0035,
          repetition_penalty_presence: 0,
          phrase_rep_pen: "medium",
          mirostat_lr: 1.0,
          mirostat_tau: 0,
          min_p: 0.05,
        },
      },
    ],
  },
  {
    comment: "Erato-Dragonfruit",
    rows: [
      {
        name: "Erato-Dragonfruit",
        modelTarget: "erato",
        desc: "Fruity and vivid, complex sampler chain with mirostat for elaborate and colorful prose.",
        i18n: {
          ja: "複雑なサンプラーチェーンとミロスタットで鮮やかで精巧な文体を実現。",
          "pt-BR": "Vívida, cadeia complexa de amostradores com mirostat para prosa colorida e elaborada.",
          "es-419": "Vívido, con cadena compleja de muestreo y mirostat para prosa elaborada y colorida.",
        },
        parameters: {
          order: [0, 5, 9, 10, 8, 4],
          temperature: 1.37,
          max_length: 150,
          min_length: 1,
          top_k: 0,
          top_p: 1.0,
          top_a: 0.1,
          typical_p: 0.875,
          tail_free_sampling: 0.87,
          repetition_penalty: 3.25,
          repetition_penalty_range: 6000,
          repetition_penalty_slope: 3.25,
          repetition_penalty_frequency: 0,
          repetition_penalty_presence: 0,
          phrase_rep_pen: "off",
          mirostat_lr: 0.2,
          mirostat_tau: 4.0,
          min_p: 0.035,
        },
      },
    ],
  },
  {
    comment: "Erato-Golden Arrow",
    rows: [
      {
        name: "Erato-Golden Arrow",
        modelTarget: "erato",
        desc: "Classic and balanced, standard tail-free sampling for coherent, flowing narrative.",
        i18n: {
          ja: "クラシックでバランスの取れた、テールフリーサンプリングによる一貫した滑らかなナラティブ。",
          "pt-BR": "Clássica e equilibrada, tail-free padrão para uma narrativa coerente e fluida.",
          "es-419": "Clásico y equilibrado, tail-free estándar para narrativa coherente y fluida.",
        },
        parameters: {
          order: [9, 2],
          temperature: 1.0,
          max_length: 150,
          min_length: 1,
          top_k: 0,
          top_p: 0.995,
          top_a: 1.0,
          typical_p: 1.0,
          tail_free_sampling: 0.87,
          repetition_penalty: 1.5,
          repetition_penalty_range: 2240,
          repetition_penalty_slope: 1.0,
          repetition_penalty_frequency: 0,
          repetition_penalty_presence: 0,
          phrase_rep_pen: "light",
          mirostat_lr: 1.0,
          mirostat_tau: 0,
          min_p: 0,
        },
      },
    ],
  },
  {
    comment: "Erato-Wilder",
    rows: [
      {
        name: "Erato-Wilder",
        modelTarget: "erato",
        desc: "Wild and expansive, high top-K (300) for more varied and adventurous outputs.",
        i18n: {
          ja: "高いトップK（300）による多様で冒険的な出力。",
          "pt-BR": "Selvagem e expansiva, alto top-K (300) para resultados mais aventureiros.",
          "es-419": "Salvaje y amplio, top-K alto (300) para resultados variados y aventureros.",
        },
        parameters: {
          order: [9, 10],
          temperature: 1.0,
          max_length: 150,
          min_length: 1,
          top_k: 300,
          top_p: 0.98,
          top_a: 0.004,
          typical_p: 0.96,
          tail_free_sampling: 0.96,
          repetition_penalty: 1.48,
          repetition_penalty_range: 2240,
          repetition_penalty_slope: 0.64,
          repetition_penalty_frequency: 0,
          repetition_penalty_presence: 0,
          phrase_rep_pen: "medium",
          mirostat_lr: 1.0,
          mirostat_tau: 0,
          min_p: 0.02,
        },
      },
    ],
  },
  {
    comment: "Erato-Zany Scribe",
    rows: [
      {
        name: "Erato-Zany Scribe",
        modelTarget: "erato",
        desc: "Zany and unpredictable, high frequency/presence penalties for maximally varied outputs.",
        i18n: {
          ja: "高い頻度・存在ペナルティによる最大限に多様な出力。",
          "pt-BR": "Excêntrica, altas penalidades de presença/frequência para máxima variedade.",
          "es-419": "Excéntrico e impredecible, con altas penalizaciones para máxima variedad.",
        },
        parameters: {
          order: [9, 2],
          temperature: 1.0,
          max_length: 150,
          min_length: 1,
          top_k: 0,
          top_p: 0.99,
          top_a: 1.0,
          typical_p: 1.0,
          tail_free_sampling: 0.99,
          repetition_penalty: 1.0,
          repetition_penalty_range: 64,
          repetition_penalty_slope: 1.0,
          repetition_penalty_frequency: 0.75,
          repetition_penalty_presence: 1.5,
          phrase_rep_pen: "medium",
          mirostat_lr: 1.0,
          mirostat_tau: 1.0,
          min_p: 0.08,
        },
      },
    ],
  },
];
