import type { Client, Message } from "discord.js";
import type { ForcedMention } from "@/types/discord/mentions";
import type { StructuredContextItem } from "@/types/misc/context";
import type { StreamingContext } from "@/types/tool/interfaces";
import type { ChatIncoming, ChatReminderData, ManualTriggerInvoker, TextQuotaSource } from "@/utils/chat/types";

export type { ChatIncoming, ManualTriggerInvoker, TextQuotaSource } from "@/utils/chat/types";
export type ChatInvocation = ChatIncoming;

export function normalizeChatInvocation(
  client: Client,
  message: Message,
  isFromQueue: boolean,
  isManuallyTriggered?: boolean,
  forceReason?: boolean,
  reasoningQuery?: string,
  llmOverrideCodename?: string,
  isStopResponse?: boolean,
  retryCount = 0,
  skipLock = false,
  reminderRecipientID?: string,
  reminderData?: ChatReminderData,
  selectedPersonaId?: number,
  isPersonaJob = false,
  isUserImpersonation = false,
  impersonatedUserId?: string,
  textQuotaSource: TextQuotaSource = "user",
  textQuotaTriggerKey?: string,
  textQuotaUserDiscId?: string,
  manualSystemPrompt?: string,
  manualPrefill?: string,
  naiContinuationPrefill?: string,
  emptyResponseFinishReason?: string,
  injectedContextItems?: StructuredContextItem[],
  forcedMentions?: ForcedMention[],
  manualTriggerInvoker?: ManualTriggerInvoker,
  manualStreamingContextOverrides?: Partial<StreamingContext>,
): ChatIncoming {
  return {
    client,
    message,
    isFromQueue,
    isManuallyTriggered,
    forceReason,
    reasoningQuery,
    llmOverrideCodename,
    isStopResponse,
    retryCount,
    skipLock,
    reminderRecipientID,
    reminderData,
    selectedPersonaId,
    isPersonaJob,
    isUserImpersonation,
    impersonatedUserId,
    textQuotaSource,
    textQuotaTriggerKey,
    textQuotaUserDiscId,
    manualSystemPrompt,
    manualPrefill,
    naiContinuationPrefill,
    emptyResponseFinishReason,
    injectedContextItems,
    forcedMentions,
    manualTriggerInvoker,
    manualStreamingContextOverrides,
  };
}

export function createChatInvocation(
  client: Client,
  message: Message,
  isFromQueue: boolean,
  isManuallyTriggered?: boolean,
  forceReason?: boolean,
  reasoningQuery?: string,
  llmOverrideCodename?: string,
  isStopResponse?: boolean,
  retryCount = 0,
  skipLock = false,
  reminderRecipientID?: string,
  reminderData?: ChatReminderData,
  selectedPersonaId?: number,
  isPersonaJob = false,
  isUserImpersonation = false,
  impersonatedUserId?: string,
  textQuotaSource: TextQuotaSource = "user",
  textQuotaTriggerKey?: string,
  textQuotaUserDiscId?: string,
  manualSystemPrompt?: string,
  manualPrefill?: string,
  naiContinuationPrefill?: string,
  emptyResponseFinishReason?: string,
  injectedContextItems?: StructuredContextItem[],
  forcedMentions?: ForcedMention[],
  manualTriggerInvoker?: ManualTriggerInvoker,
  manualStreamingContextOverrides?: Partial<StreamingContext>,
): ChatIncoming {
  return normalizeChatInvocation(
    client,
    message,
    isFromQueue,
    isManuallyTriggered,
    forceReason,
    reasoningQuery,
    llmOverrideCodename,
    isStopResponse,
    retryCount,
    skipLock,
    reminderRecipientID,
    reminderData,
    selectedPersonaId,
    isPersonaJob,
    isUserImpersonation,
    impersonatedUserId,
    textQuotaSource,
    textQuotaTriggerKey,
    textQuotaUserDiscId,
    manualSystemPrompt,
    manualPrefill,
    naiContinuationPrefill,
    emptyResponseFinishReason,
    injectedContextItems,
    forcedMentions,
    manualTriggerInvoker,
    manualStreamingContextOverrides,
  );
}
